### ISSUE TITLE
`group` throws an error if you give it a `label`

### ISSUE THREAD

**Issue by ianchesal** [Gusto/buildkite-builder#93]
I'm getting an error trying to put a `label` inside a `group` block. If I drop the label it works just fine.

Here is the reproduction `pipeline.rb` file:

```
Buildkite::Builder.pipeline do
  group do
    label 'Group'
    command do
      label 'Step 1'
      command 'echo "Hello, world!"'
    end
    command do
      label 'Step 2'
      command 'echo "Hello, world!"'
    end
  end
end
```

The error I get is:

```
/Users/ianchesal/src/kubernetes/.buildkite/pipelines/error/pipeline.rb:3:in `block (2 levels) in <main>': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/group.rb:28:in `instance_eval'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/group.rb:28:in `initialize'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/extensions/steps.rb:21:in `new'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/extensions/steps.rb:21:in `group'
	from /Users/ianchesal/src/kubernetes/.buildkite/pipelines/error/pipeline.rb:2:in `block in <main>'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/pipeline.rb:68:in `instance_eval'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/pipeline.rb:68:in `block in to_h'
	from /usr/local/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/logging_utils.rb:9:in `benchmark'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/pipeline.rb:67:in `to_h'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/pipeline.rb:78:in `to_yaml'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/commands/preview.rb:12:in `run'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/commands/abstract.rb:54:in `execute'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/commands/abstract.rb:25:in `execute'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/lib/buildkite/builder/commands.rb:27:in `run'
	from /usr/local/bundle/gems/buildkite-builder-3.8.0/exe/buildkite-builder:6:in `<top (required)>'
	from /usr/local/bundle/bin/buildkite-builder:25:in `load'
	from /usr/local/bundle/bin/buildkite-builder:25:in `<main>'
```

If I change `pipelines.rb` to the following it renders without issue:

```
Buildkite::Builder.pipeline do
  group do
    command do
      label 'Step 1'
      command 'echo "Hello, world!"'
    end
    command do
      label 'Step 2'
      command 'echo "Hello, world!"'
    end
  end
end
```

**Comment by ianchesal** [comment]
I should have mentioned: I'm using `v3.8.0` -- looks like group.rb was restructured in a later release. I don't see any newer releases on your release page though.

**Comment by technicalpickles** [comment]
@ianchesal 4.1.2 is the latest release, and it is what we use. Can you try on that version, and let me know if it works?

I'm not sure what happened to the "Releases" on the sidebar, but we should automate that to keep things in sync.

**Comment by ianchesal** [comment]
@technicalpickles looks like 4.1.2 isn't on docker-hub yet: https://hub.docker.com/r/gusto/buildkite-builder/tags

```
❯ docker run -it --entrypoint='' -v `pwd`:/app gusto/buildkite-builder:4.1.2 bash
Unable to find image 'gusto/buildkite-builder:4.1.2' locally
docker: Error response from daemon: manifest for gusto/buildkite-builder:4.1.2 not found: manifest unknown: manifest unknown.
See 'docker run --help'.

```

**Comment by ianchesal** [comment]
But trying `4.1.0` and it renders correctly. Will upgrade to that. Thanks!

**Comment by ngan** [comment]
Hey @ianchesal 4.1.2 has been released on docker hub. Sorry about that.
